### PR TITLE
Add yeh-barree support

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Comment by khaledhosny** [comment]
That is a tough one. An easy improvement is to make the isolated `yehbarree-ar` set on the base line (I like my returning yeh's setting on the base line). I tried to avoid any horizontal lines, but a returning yeh can’t return without one.

The final glyph is a bit problematic, though. The half-thickness space is used between letters, parts of the same letter use 1/10 space:
Screen Shot 2021-06-07 at 1 46 27 PM

Here is my alternate proposal, WDYT:
Screen Shot 2021-06-07 at 1 58 22 PM

**Comment by simoncozens** [comment]
It looks fine, but I am wondering why there is a need to raise the start of the ے above the baseline?

bitmap

**Comment by khaledhosny** [comment]
Than Noto example is poor, this is more how it should look in Naskh (but the raised part is the tooth of the ن):
image

In old Kufic, however, it always has a raised part:
image

**Comment by khaledhosny** [comment]
image
image

**Pull request merged**
